# Generated by Django 3.2.9 on 2021-12-14 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GuildApplicants',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('char_name', models.CharField(max_length=32, verbose_name='Character Name')),
                ('char_role', models.CharField(max_length=32, verbose_name='Character Role')),
                ('warcraft_logs', models.URLField(verbose_name='Warcraft Logs URL')),
                ('speed_test', models.URLField(verbose_name='Speed Test URL')),
                ('spoken_langs', models.CharField(max_length=32, verbose_name='Spoken Languages')),
                ('native_lang', models.CharField(max_length=32, verbose_name='Native Language')),
                ('raid_1', models.BooleanField(default=False, verbose_name='Raid 1')),
                ('raid_2', models.BooleanField(default=False, verbose_name='Raid 2')),
                ('raid_exp', models.TextField(blank=True, verbose_name='Raid Experience')),
                ('why_join', models.TextField(blank=True, verbose_name='Why Zero')),
                ('contact_info', models.CharField(max_length=128, verbose_name='Contact Information')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined')], default='pending', max_length=8)),
            ],
            options={
                'verbose_name': 'Guild Applicants',
                'verbose_name_plural': 'Guild Applicants',
            },
        ),
        migrations.CreateModel(
            name='GuildNews',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='The Title of the post.', max_length=64, verbose_name='Title')),
                ('display_name', models.CharField(help_text='This should be your primary alias.', max_length=32, verbose_name='Display Name')),
                ('description', models.TextField(help_text='The entire body and full text of the post. Newlines are allowed.', verbose_name='Description Body')),
                ('published', models.BooleanField(default=False, help_text='The post will not show up unless this is checked.', verbose_name='Published')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Guild News',
                'verbose_name_plural': 'Guild News',
            },
        ),
        migrations.CreateModel(
            name='GuildProfile',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='Discord ID')),
                ('main_char', models.CharField(max_length=32, unique=True, verbose_name='Main Character')),
                ('main_class', models.CharField(max_length=32, verbose_name='Main Class')),
                ('main_role', models.CharField(max_length=32, verbose_name='Main Role')),
                ('user_description', models.TextField(blank=True, verbose_name='User Description')),
                ('show_in_roster', models.BooleanField(default=True, verbose_name='Show in Roster')),
                ('twitch_username', models.CharField(blank=True, max_length=32, verbose_name='Twitch Username')),
                ('live_on_twitch', models.BooleanField(default=False, verbose_name='Twitch Live Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Guild Profile',
                'verbose_name_plural': 'Guild Profiles',
            },
        ),
        migrations.CreateModel(
            name='TwitchToken',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('access_token', models.CharField(blank=True, max_length=32)),
                ('expiration_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Twitch Token',
                'verbose_name_plural': 'Twitch Tokens',
            },
        ),
    ]
